ServerRoot /config/.XDG/selkies-cups
ServerBin /config/.XDG/selkies-cups/bin
DataDir /usr/share/cups
StateDir /config/.XDG/selkies-cups/state
CacheDir /config/.XDG/selkies-cups/cache
RequestRoot /config/.XDG/selkies-cups/spool
TempDir /config/.XDG/selkies-cups/tmp
LogFileGroup 1000
AccessLog /config/.XDG/selkies-cups/access.log
PageLog /config/.XDG/selkies-cups/page.log
ErrorLog /config/.XDG/selkies-cups/error.log
